### ISSUE TITLE
Bug: Something went wrong with the vimOpt when looking at folders

### ISSUE THREAD

**Issue by jrmiller82** [jhpyle/docassemble#17]
Steps to reproduce: 

1. Spin up new docker instance with fresh pull
2. Do NOT change any vimopt configuration
3. Click playground
4. Click folders OR Click Modules OR Click Templates
5. click sources
6. See below error. 

```
Error

    UnboundLocalError: local variable 'vimOpt' referenced before assignment

Log

Traceback (most recent call last):
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/flask_user/decorators.py", line 29, in decorated_view
    return func(*args, **kwargs)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/flask_user/decorators.py", line 76, in decorated_view
    return func(*args, **kwargs)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/webapp/server.py", line 7069, in playground_files
    });""" + extra_command + """
UnboundLocalError: local variable 'vimOpt' referenced before assignment
```

**Comment by jrmiller82** [comment]
I added a `vim: true` to my config, restarted docassemble, went to playground, and still have the same issues. Perhaps it has something to do with the other editors on those folder pages? 

(I'll promise to read some source code soon and help out with the actual coding; it's been awhile but I can speak python too)

**Comment by jhpyle** [comment]
Sorry!  I am in the process of uploading the fix.  If you set `vim: false` you shouldn't get the error.

**Comment by jrmiller82** [comment]
No worries! Let me know when you've fixed it and I'll pull a new docker image and test for you.

**Comment by jhpyle** [comment]
Ok, I have tested it and the problem is fixed in the latest docker image.

**Comment by jrmiller82** [comment]
Thanks. Pulling it now.

**Comment by jrmiller82** [comment]
Confirmed working now. Thanks!
