### ISSUE TITLE
Occasionally getting 500 error on login after upgrade

### ISSUE THREAD

**Issue by bennlich** [jhpyle/docassemble#192]
I recently upgraded (system + python) to 0.4.80.

When my colleague tries to login, he gets a 500 error:

![image](https://user-images.githubusercontent.com/704368/64270431-5da3ce80-cef0-11e9-9eac-19184820a351.png)

I receive this error e-mail:

```
There was an error in the docassemble application.
The error message was:

ProgrammingError: 
ProgrammingError: (psycopg2.errors.UndefinedTable) relation "globalobjectstorage" does not exist
LINE 2: FROM globalobjectstorage 
             ^

[SQL: SELECT globalobjectstorage.id AS globalobjectstorage_id, globalobjectstorage.key AS globalobjectstorage_key, globalobjectstorage.value AS globalobjectstorage_value, globalobjectstorage.encrypted AS globalobjectstorage_encrypted, globalobjectstorage.user_id AS globalobjectstorage_user_id, globalobjectstorage.temp_user_id AS globalobjectstorage_temp_user_id 
FROM globalobjectstorage 
WHERE globalobjectstorage.user_id = %(user_id_1)s]
[parameters: {'user_id_1': 1}]
(Background on this error at: http://sqlalche.me/e/f405)
  Traceback (most recent call last):  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context  cursor, statement, parameters, context  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute  cursor.execute(statement, parameters) psycopg2.errors.UndefinedTable: relation "globalobjectstorage" does not exist LINE 2: FROM globalobjectstorage   ^   The above exception was the direct cause of the following exception:  Traceback (most recent call last):  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request  rv = self.dispatch_request()  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request  return self.view_functions[rule.endpoint](**req.view_args)  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/docassemble/webapp/server.py", line 549, in custom_login  return add_secret_to(flask_user.views._do_login_user(user, safe_next, login_form.remember_me.data))  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/flask_user/views.py", line 730, in _do_login_user  signals.user_logged_in.send(current_app._get_current_object(), user=user)  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/blinker/base.py", line 267, in send  for receiver in self.receivers_for(sender)]  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/blinker/base.py", line 267, in   for receiver in self.receivers_for(sender)]  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/docassemble/webapp/server.py", line 18534, in _on_user_login  login_or_register(sender, user, **extra)  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/docassemble/webapp/server.py", line 18504, in login_or_register  for object_entry in GlobalObjectStorage.query.filter_by(user_id=user.id).all():  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3178, in all  return list(self)  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3334, in __iter__  return self._execute_and_instances(context)  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3359, in _execute_and_instances  result = conn.execute(querycontext.statement, self._params)  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 988, in execute  return meth(self, multiparams, params)  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection  return connection._execute_clauseelement(self, multiparams, params)  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement  distilled_params,  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context  e, statement, parameters, cursor, context  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception  util.raise_from_cause(sqlalchemy_exception, exc_info)  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause  reraise(type(exception), exception, tb=exc_tb, cause=cause)  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 152, in reraise  raise value.with_traceback(tb)  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context  cursor, statement, parameters, context  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute  cursor.execute(statement, parameters) sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "globalobjectstorage" does not exist LINE 2: FROM globalobjectstorage   ^  [SQL: SELECT globalobjectstorage.id AS globalobjectstorage_id, globalobjectstorage.key AS globalobjectstorage_key, globalobjectstorage.value AS globalobjectstorage_value, globalobjectstorage.encrypted AS globalobjectstorage_encrypted, globalobjectstorage.user_id AS globalobjectstorage_user_id, globalobjectstorage.temp_user_id AS globalobjectstorage_temp_user_id  FROM globalobjectstorage  WHERE globalobjectstorage.user_id = %(user_id_1)s] [parameters: {'user_id_1': 1}] (Background on this error at: http://sqlalche.me/e/f405) 

The referer URL was https://mycitations.uat.courts.ca.gov/user/sign-in?next=https%3A%2F%2Fmycitations.uat.courts.ca.gov%2Fplayground
```

We think it is some kind of browser cacheing issue, as he is able to log in successfully from an incognito window.

**Comment by jhpyle** [comment]
Are you setting `CONTAINERROLE` when you invoke `docker run`, and if so, what value are you using for `CONTAINERROLE`?

**Comment by bennlich** [comment]
No I am not setting `CONTAINERROLE`. My run command is:

```
sudo docker run --env-file=env.list -d -p 8080:80 bennlichh/docassemble
```

and my env.list is:

```
DAPYTHONVERSION=3
BEHINDHTTPSLOADBALANCER=true
AZUREENABLE=true
AZURECONTAINER=<put storage container name here>
AZUREACCOUNTNAME=<put storage account name here>
AZUREACCOUNTKEY=<put the storage account key here>
```

**Comment by bennlich** [comment]
I'm now seeing the error on my own log-in attempts, both incognito and not.

Following the link in `(Background on this error at: http://sqlalche.me/e/f405)`, maybe it's a DB disconnection issue?

**Comment by jhpyle** [comment]
The error message is consistent with what you would see if you started a cluster of one or more servers connected to the same database, but you failed to start a central server prior to starting a web application server.

A central server needs to create the database tables.  The central server is indicated by the `CONTAINERROLE` of `cron` or `all`.

If your `CONTAINERROLE` is unset, or is set to `all` (the default), or is set to `cron`, then during the `initialize` service, the startup script will create the database tables in the SQL database if any are missing.  This is done at step "30" of the `initialize` service.  You can check the logs for the `initialize` service by viewing the `/var/log/supervisor/initialize*` files to see if there was an error at step 30.

**Comment by bennlich** [comment]
Interestingly, my colleague who originally noticed this is now able to log in without issue, and I am the only one who is unable to log in. We are both attempting logins as admin.

**Comment by bennlich** [comment]
Ah, yes. There were some problems with step 30:

```
29
There are postgres files on Azure
Found postgres/docassemble on Azure
Copying postgres/docassemble to docassemble
Postgres database backup directory is /tmp/tmp.RnLgaSoHJE
Restoring postgres database docassemble
ERROR:  database "docassemble" does not exist
30
fix_postgresql_tables: skipping because alembic is in use.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidForeignKey: there is no unique constraint matching given keys for referenced table "user"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/docassemble/webapp/create_tables.py", line 142, in <module>
    main()
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/docassemble/webapp/create_tables.py", line 137, in main
    db.create_all()
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 1033, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 1025, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 4294, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2036, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1607, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/sql/visitors.py", line 132, in traverse_single
    return meth(obj, **kw)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/sql/ddl.py", line 781, in visit_metadata
    _is_metadata_operation=True,
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/sql/visitors.py", line 132, in traverse_single
    return meth(obj, **kw)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/sql/ddl.py", line 826, in visit_table
    include_foreign_key_constraints,
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidForeignKey) there is no unique constraint matching given keys for referenced table "user"

[SQL: 
CREATE TABLE globalobjectstorage (
	id SERIAL NOT NULL, 
	key TEXT, 
	value TEXT, 
	encrypted BOOLEAN DEFAULT true NOT NULL, 
	user_id INTEGER, 
	temp_user_id INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES "user" (id) ON DELETE CASCADE, 
	FOREIGN KEY(temp_user_id) REFERENCES tempuser (id) ON DELETE CASCADE
)

]
(Background on this error at: http://sqlalche.me/e/f405)
31
```

**Comment by jhpyle** [comment]
It doesn't make sense that a SQL error would be connected to different behavior experienced by two different people both trying to log in as the same user from different devices.  It is conceivable that maybe one thread is in an error state and another is not.  Doing a restart might change things.

I have seen instances in the past where SQLAlchemy unpredictably throws exceptions based on foreign key specification.  I'll work on making sure that those errors never arise.  (Though it is tough because I can never reproduce the error.)

**Comment by bennlich** [comment]
I did a little more diagnosing. I don't think I got any closer to the root cause, but the behavior is interesting.

After rebooting the container, log-in from a normal browser tab consistently failed, and log-in from an incognito window consistently succeeded. I was able to reproduce this in two different browsers.

In a normal browser tab, when I cleared my cookies and went directly to the sign-in page, I was able to consistently log in successfully.

In a normal browser tab, when I cleared my cookies, went to the main interview page, and then to the sign-in page, log in consistently failed.

Seems like slightly different code paths were getting followed? Or maybe I was just getting assigned to the good thread and the bad thread in very consistent ways?

I noticed that if I navigated to an interview page first, I had an extra `secret` cookie that was not present when going directly to the sign-in page.

**Comment by jhpyle** [comment]
Ok, that makes sense.  When you log in, it will do a query on `globalobjectstorage` (and trigger the error) only if your Flask session cookie is connected with an anonymous session.  So that would explain the different results you were seeing.  But the underlying issue is that your database is missing a table.

Does your Configuration point to a particular database backend under the `db` directive?  If so, can you tell me what version of PostgreSQL the server is running?

**Comment by jhpyle** [comment]
Before upgrading, had anyone edited the tables in SQL to add columns to the `user` table, by any chance?

**Comment by bennlich** [comment]
Here's the `db` directive. I think it's the default?

```
db:
  prefix: postgresql+psycopg2://
  name: docassemble
  user: docassemble
  password: abc123
  host: null
  port: null
  table prefix: null
```

PostgreSQL 9.6.15 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

Nope, no columns added to the `user` table.

**Comment by bennlich** [comment]
Any recommendations for how to get my missing table back? If I destroy this container and create a new one, I'm guessing I'll have the same issue because the DB backup on azure is probably also missing the table.

I don't need to keep any of the data in this database--am fine obliterating it. Just not sure how to go about it smoothly.

**Comment by jhpyle** [comment]
If you don't care about the data in the SQL database, I'd do `docker stop -t 600`, `docker rm`, and then go into Azure and delete the contents of the `postgres` folder, as well as the contents of `files/000`.  I would also recommend doing a `docker pull` to get the latest version.  Then do a fresh `docker run`.  It might be a random SQLAlchemy fluke that the table didn't get created.

**Comment by bennlich** [comment]
This worked (though I forgot to delete files/000). Thank you!

**Comment by bennlich** [comment]
However, I'm now periodically getting these error emails:

```
IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "userdictkeys" violates foreign key constraint "userdictkeys_temp_user_id_fkey"
DETAIL:  Key (temp_user_id)=(61247) is not present in table "tempuser".

[SQL: INSERT INTO userdictkeys (filename, key, user_id, temp_user_id) VALUES (%(filename)s, %(key)s, %(user_id)s, %(temp_user_id)s) RETURNING userdictkeys.indexno]
[parameters: {'temp_user_id': 61247, 'filename': 'docassemble.jcc.abilitytopay:data/questions/interview.yml', 'user_id': None, 'key': 'zhBPwv1WD73pMvYO81BBCrwZSJDyDdy1'}]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

Could this be because docassemble is trying to look up an old cookie in a fresh database?

**Comment by jhpyle** [comment]
I think this resulted from the fact that session information persisted in Redis while the SQL was reset.  Redis contained information about temporary user 61247 but the SQL database no longer had information about temporary user 61247.

**Comment by bennlich** [comment]
Aha. How would I go about wiping Redis as well? Is that safe to do?

**Comment by jhpyle** [comment]
In addition to deleting the `postgres` folder on Azure (per the instructions above), you could have deleted the `redis.db` file.  I should have recommended that.  However at this point I am not sure it matters, unless you extended your session lifetime past the default of 12 hours.

**Comment by bennlich** [comment]
Hmmm. I am continuing to see this error as I try to log in with old devices. I don't believe I extended the session lifetime. Is this the session lifetime you're talking about?

https://docassemble.org/docs/config.html#session%20lifetime%20seconds

Sounds like the default might be 31 days?

**Comment by jhpyle** [comment]
Sorry, you're right.  I was thinking of another timeout that is 12 hours by default.

I would wait until a time when nobody is using the server and then `docker exec` inside, run `redis-cli`, and issue the command `FLUSHALL`.  (This will also remove API keys if you have any.)

**Comment by bennlich** [comment]
Worked! Thanks.
