### ISSUE TITLE
NameError: name 'defaultDaServer' is not defined

### ISSUE THREAD

**Issue by Weijtmans** [jhpyle/docassemble#193]
I'm trying to use the word add-in in the online office365 environment. However I get the following error: NameError: name 'defaultDaServer' is not defined

The log shows the following:
Traceback (most recent call last):
  File "/usr/share/docassemble/local3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/docassemble/local3.6/lib/python3.6/site-packages/docassemble/webapp/server.py", line 14762, in playground_office_taskpane
    return render_template('pages/officeouter.html', page_title=word("Docassemble Playground"), tab_title=word("Playground"), defaultDaServer=defaultDaServer, extra_js=Markup("\n        <script>" + indent_by(variables_js(office_mode=True), 9) + "        </script>")), 200

**Comment by jhpyle** [comment]
What version are you running on your Docassemble server?

**Comment by jhpyle** [comment]
Sorry about that.  Try upgrading to 0.5.4.

**Comment by jhpyle** [comment]
I believe this was fixed in 0.5.4, so I am closing the issue.
