### ISSUE TITLE
Interview cacheing issue?

### ISSUE THREAD

**Issue by bennlich** [jhpyle/docassemble#197]
Occasionally, when I go to `/updatepackages` and update my interview package from a github branch, my changes do not show up when I run a new interview.

My most recent change was to add a `maxlength: 300` limit to one of my inputs.

I've logged into the container and inspected what I believe is the interview file used by docassemble, located in `/usr/share/docassemble/local3.5/lib/python3.5/site-packages/docassemble/<my-package-name>`. Is that the right place to look?

The interview yaml is up to date, but the running interview does not reflect the new `maxlength: 300` constraint. Is it possible that docassemble has not properly re-imported my python package?

In a different environment, I have tested the same interview at the same commit sha, and my change is present, so I this can't be an interview syntax error.

Wondering how I might further diagnose.

**Comment by jhpyle** [comment]
After Package Management runs `pip` to install the package, it triggers a system "restart" by triggering the `reset` service through `supervisord`.  This changes the timestamp on `/usr/share/docassemble/webapp/docassemble.wsgi`, and the change to the timestamp is a signal to Apache/mod_wsgi that it should reload all the Python modules.  It also restarts some other services that depend on Python.

Particularly on a server that is in use, it can take a minute for the reload process to actually happen.  I think this is in part because Apache/mod_wsgi tries to provide uninterrupted service as the requests are coming in, so it doesn't actually reload the Python modules until there is a appropriate time to do so.  So it could be the case that if you give it a minute and then try your interview, you'll see the changes reflected.

Another possibility is that there is a failure in the triggering of the `reset` service, or a failure in the `reset` service itself.  You can look in the logs (`/usr/share/docassemble/log/docassemble.log`, `/usr/share/docassemble/log/worker.log`, `/var/log/supervisor/reset*`) to see if you see any errors around the time package installation finishes.

**Comment by bennlich** [comment]
Aha. It looks like my missing database table (described in https://github.com/jhpyle/docassemble/issues/192) may also be the cause of this issue. During a reset after a package update, I see this in the reset logs:

```
fix_postgresql_tables: skipping because alembic is in use.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidForeignKey: there is no unique constraint matching given keys for referenced table "user"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/docassemble/webapp/restart.py", line 35, in <module>
    main()
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/docassemble/webapp/restart.py", line 17, in main
    docassemble.webapp.create_tables.main()
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/docassemble/webapp/create_tables.py", line 137, in main
    db.create_all()
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 1033, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/flask_sqlalchemy/__init__.py", line 1025, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 4294, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2036, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1607, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/sql/visitors.py", line 132, in traverse_single
    return meth(obj, **kw)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/sql/ddl.py", line 781, in visit_metadata
    _is_metadata_operation=True,
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/sql/visitors.py", line 132, in traverse_single
    return meth(obj, **kw)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/sql/ddl.py", line 826, in visit_table
    include_foreign_key_constraints,
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/share/docassemble/local3.5/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidForeignKey) there is no unique constraint matching given keys for referenced table "user"

[SQL: 
CREATE TABLE globalobjectstorage (
	id SERIAL NOT NULL, 
	key TEXT, 
	value TEXT, 
	encrypted BOOLEAN DEFAULT true NOT NULL, 
	user_id INTEGER, 
	temp_user_id INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES "user" (id) ON DELETE CASCADE, 
	FOREIGN KEY(temp_user_id) REFERENCES tempuser (id) ON DELETE CASCADE
)

]
(Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by bennlich** [comment]
I believe I fixed this by obliterating the database directory and booting up a new container. See https://github.com/jhpyle/docassemble/issues/192 for details. I will re-open if I see this behavior again.
