### ISSUE TITLE
Permission errors trying to install a new package

### ISSUE THREAD

**Issue by cediorio** [jhpyle/docassemble#22]
I'm trying to install a package that I'm authoring offline. I've had it running before using an older docker image. I just refreshed the image today and am now receiving the following errors when I try to upload and install a new package (from a clean docker image [volumes and containers all removed]):

```
pip log:
pip install --quiet --prefix=/usr/share/docassemble/local --src=/tmp/tmpzP1mf8 --log-file=/tmp/tmp3Zd3m1 --upgrade /usr/share/docassemble/files/000/000/000/004/file.zip
The directory '/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /usr/share/docassemble/files/000/000/000/004/file.zip
  Running setup.py (path:/tmp/pip-YFUcus-build/setup.py) egg_info for package from file:///usr/share/docassemble/files/000/000/000/004/file.zip
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "", line 1, in 
      File "/tmp/pip-YFUcus-build/setup.py", line 58, in 
        package_data=find_package_data(where='docassemble/equityAssist/', package='docassemble.equityAssist'),
      File "/tmp/pip-YFUcus-build/setup.py", line 16, in find_package_data
        for name in os.listdir(where):
    OSError: [Errno 2] No such file or directory: 'docassemble/equityAssist/'
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-YFUcus-build/
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-YFUcus-build/
Exception information:
Traceback (most recent call last):
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-YFUcus-build/
```

Any ideas?

**Comment by jhpyle** [comment]
In your zip file, there should be a folder called `docassemble` and within that folder there should be a subfolder called `equityAssist` and within that subfolder there should be a subfolder called `data`.  Is that the case?
I am still trying to figure out why pip is using `/root/.cache` instead of `/var/www/.cache`...

**Comment by cediorio** [comment]
Here's the directory hierarchy leading down to the yml files: docassemble-equityAssist > docassemble > - equityassist > data > questions.

I stopped the docker container, cleared all the volumes/images, and started up a clean version. I then downloaded a new template and manually transferred my yml and templates in and was able to successfully install. No idea what I must have done - the dir hierarchy above looks correct, doesn't it?

I am, however, still getting the /root/.cache errors, as follows:
```
The directory '/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/root/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/root/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```

Doesn't appear to make any difference, but am puzzled as to why they occur...

**Comment by jhpyle** [comment]
If it was `docassemble/equityassist/data` as opposed to `docassemble/equityAssist/data`, then that would explain the "file not found" error.  The `setup.py` file needs to correspond exactly to the folder structure.

The next feature on my to-do list is the uploading of packages into the Playground.  This may help authors who edit files outside of the web browser.

**Comment by jhpyle** [comment]
I believe this issue has been addressed, so I am closing it.
