### ISSUE TITLE
UnicodeDecodeError in the Docassemble Demo

### ISSUE THREAD

**Issue by tienne-B** [jhpyle/docassemble#59]
In the Docassemble Demo, writing accented characters (É, é `00c9`, `00e9`) results in the error:
```
Error
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 126: ordinal not in range(128)
```

From the traceback:
```
Traceback (most recent call last):
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/base/parse.py", line 4228, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/base/parse.py", line 4721, in askfor
    return question.ask(user_dict, old_user_dict, the_x, iterators, missing_var, origMissingVariable)
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/base/parse.py", line 3123, in ask
    attachment_text = self.processed_attachments(user_dict) # , the_x=the_x, iterators=iterators
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/base/parse.py", line 3185, in processed_attachments
    items.append([x, self.prepare_attachment(x, user_dict, **kwargs), None])
  File "/usr/share/docassemble/local/local/lib/python2.7/site-packages/docassemble/base/parse.py", line 3656, in prepare_attachment
    the_markdown += u'---\n' + ruamel.yaml.safe_dump(modified_metadata, default_flow_style=False, default_style = '|') + "...\n"
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 126: ordinal not in range(128)
```

**Comment by jhpyle** [comment]
I am closing this for now because I think 0.2.72 addresses the issue, but feel free to reopen if the problem persists.
