### ISSUE TITLE
can't start docker image

### ISSUE THREAD

**Issue by japrogramer** [jhpyle/docassemble#647]
can't start docassemble in docker image

jhpyle/docassemble                                                  latest         7e98b4ded27a   18 months ago   8.04GB

```
mounting docassemble.webapp.run:application on /
Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/run.py", line 1, in <module>
    from docassemble.webapp.server import app as application
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/server.py", line 977, in <module>
    import docassemble.webapp.setup
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/setup.py", line 1, in <module>
    from docassemble.webapp.app_object import app
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/app_object.py", line 9, in <module>
    from flask_wtf.csrf import CSRFProtect
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask_wtf/__init__.py", line 3, in <module>
    from .csrf import CSRFProtect, CsrfProtect
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask_wtf/csrf.py", line 10, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/usr/share/docassemble/local3.8/lib/python3.8/site-packages/werkzeug/security.py)
unable to load app 0 (mountpoint='/') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
```

**Comment by BryceStevenWilley** [comment]
I can't reproduce (though there have been a few new versions since you made this comment), but it would seem like you've pulled [a pretty old version of flask-wtf somehow](https://github.com/wtforms/flask-wtf/commit/9bbdc58bf55d11df918eee23f966a428dad8a1ed), as that error was fixed in 0.15.0, and [docassemble uses 1.1.1 now](https://github.com/jhpyle/docassemble/blob/7485094cc8952c3179335453c814e8476df9c320/docassemble_webapp/setup.py#L87).  All of those pypi dependencies are pull when the container starts up, and aren't stored in the docker image itself, so that too can vary from startup-to-startup, so I'd maybe go through the [logs generated by the starting container](https://docassemble.org/docs/docker.html#troubleshooting) when it's downloading everything from pypi and see if anything unexpected happened there.
