### ISSUE TITLE
latest docker cannot start or install packages, numpy error

### ISSUE THREAD

**Issue by japrogramer** [jhpyle/docassemble#658]
it claims that there was a keyboard interrupt, but I did not do an interrupt.

```
initialize: Copying SSL certificates into position, if necessary
initialize: Testing if PostgreSQL is running
initialize: Starting PostgreSQL
initialize: Testing if the database user exists
initialize: Creating the database user
initialize: Restoring SQL database
initialize: Restoring postgres database ./docassemble
ERROR:  database "docassemble" does not exist
initialize: Testing if database exists
initialize: Obtaining default e-mail and password from mounted credentials, if available
initialize: Creating tables
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/create_tables.py", line 11, in <module>
    from docassemble.base.functions import word
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/functions.py", line 28, in <module>
    import nltk
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/nltk/__init__.py", line 133, in <module>
    from nltk.collocations import *
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/nltk/collocations.py", line 36, in <module>
    from nltk.metrics import (
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/nltk/metrics/__init__.py", line 17, in <module>
    from nltk.metrics.aline import align
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/nltk/metrics/aline.py", line 41, in <module>
    import numpy as np
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
KeyboardInterrupt
Interrupt
initialize: Configuring log server, if applicable
initialize: Starting Redis
initialize: Doing upgrading of packages
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 4: Operation not permitted
OpenBLAS blas_thread_init: RLIMIT_NPROC -1 current, -1 max
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/update.py", line 735, in <module>
    main()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/update.py", line 694, in main
    from docassemble.webapp.app_object import app  # pylint: disable=import-outside-toplevel
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/app_object.py", line 12, in <module>
    import docassemble.base.functions
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/functions.py", line 28, in <module>
    import nltk
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/nltk/__init__.py", line 133, in <module>
    from nltk.collocations import *
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/nltk/collocations.py", line 36, in <module>
    from nltk.metrics import (
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/nltk/metrics/__init__.py", line 17, in <module>
    from nltk.metrics.aline import align
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/nltk/metrics/aline.py", line 41, in <module>
    import numpy as np
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
KeyboardInterrupt
Interrupt
```

**Comment by jhpyle** [comment]
The "keyboard interrupt" message is probably caused by the fact that a `SIGINT` signal got raised due to an error.

See https://docassemble.org/docs/docker.html#install
> The operating system that runs inside of the docassemble [Docker](https://www.docker.com/) container is Ubuntu 22.04. This is a fairly recent version of Ubuntu. When using [Docker](https://www.docker.com/), it is recommended that you run a recent version of Docker and its dependencies ([containerd](https://containerd.io/) and [runC](https://github.com/opencontainers/runc)). Ubuntu 22 and Debian 11 are known to work well. (If you run Docker on Mac or Windows, it will likely start a virtual machine and then deploy the docassemble Docker container inside that virtual machine; the operating system of that virtual machine, which is likely a flavor of Linux, should be recent.) You may encounter difficult-to-diagnose problems if docassemble’s OS and software do not fully function inside the host operating system. It is difficult to predict what these errors will be. If you run the latest docassemble image on an OS that is older than Ubuntu 22, it is likely that you will encounter problems, if not right away then at a later point in time. The software in the docassemble image and Python packages is continually updated, and the latest versions of software may expect the latest versions of operating system.

I don't know exactly why you are getting the error that you are getting, but I have seen it before when the host OS and/or Docker version and/or containerd version and/or runC version is behind what the docassemble OS (Ubuntu 22.04) expects. It is a good idea to upgrade your host OS whenever you do a system upgrade.

Docker containers are not like virtual machine, which would let you run new software on an old hypervisor. With Docker, the kernel is shared between the host and the container. The boundary between host and OS is more permeable as it is with VMs. As a result, there can be a lot of weird problems when the software in the container is more modern than the host OS and its version of Docker. I can't explain why (I didn't write that software) but it has been my experience.

**Comment by japrogramer** [comment]
upgrading the host OS worked
