### ISSUE TITLE
werkzeug.safe_strp_cmp not found, can't start docassemble

### ISSUE THREAD

**Issue by japrogramer** [jhpyle/docassemble#659]
cannot start docassemble.

```
initialize: Testing if RabbitMQ is running
initialize: Starting RabbitMQ
initialize: Checking if celery is already running
initialize: Celery is not already running
initialize: Starting Celery
initialize: Getting ready to start NGINX
initialize: Not using HTTPS
initialize: Backing up NGINX
initialize: Starting websockets
initialize: Starting uwsgi
initialize: Stopping the nascent web server
initialize: Starting NGINX
initialize: Test localhost through HTTP
initialize: Registering this server
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/register.py", line 7, in <module>
    from docassemble.webapp.app_object import app
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/app_object.py", line 9, in <module>
    from flask_wtf.csrf import CSRFProtect
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask_wtf/__init__.py", line 3, in <module>
    from .csrf import CSRFProtect, CsrfProtect
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask_wtf/csrf.py", line 10, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/usr/share/docassemble/local3.8/lib/python3.8/site-packages/werkzeug/security.py)
initialize: Starting cron
initialize: Starting exim4
initialize: Finished initializing

```

**Comment by japrogramer** [comment]
container image version.
```
latest          a6b51e2a6be4   19 months ago   8.03GB
```

**Comment by jhpyle** [comment]
I would suggest doing a system upgrade. That is a very old container image. The latest version uses Python 3.10, and you are on Python 3.8. It might be the case that there is a mismatch of versions of Python dependencies on your machine, which is causing that error.

**Comment by japrogramer** [comment]
@jhpyle I did but I got this even more confusing error. https://github.com/jhpyle/docassemble/issues/658, this error happpens running on latest from today.
