### ISSUE TITLE
Variables with datatype: raw causing UnboundLocalError

### ISSUE THREAD

**Issue by jkscheibner** [jhpyle/docassemble#660]
Question blocks which set a variable with datatype: raw generate an UnboundLocalError

```
Log

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/server.py", line 7472, in index
    data = repr(data)
UnboundLocalError: local variable 'data' referenced before assignment
```

**Comment by jhpyle** [comment]
Sorry about that. I fixed the issue in 1.4.60.

It looks like you are still using Python 3.8, so I think you will need to do a [system upgrade](https://docassemble.org/docs/docker.html#upgrading) to upgrade to 1.4.60.
