### ISSUE TITLE
JSON representation of code generated fields containing choices results in error

### ISSUE THREAD

**Issue by staffanm** [jhpyle/docassemble#681]
The following example returns a interview with a single, multiple choice field as expected

```yaml
mandatory: true
question: code generated fields and json representation
fields:
  - code: |
      [{"My label": "myfield",
       "choices": ["one","two"]
       }]
```

However, if I try to access the JSON representation of the question by adding "&json=1" to the URL, the following stack trace is generated:

```
Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 12909, in index
    data.update(interview_status.as_data(user_dict))
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 1257, in as_data
    the_field['choices'] = self.get_choices_data(field, the_default, the_user_dict, encode=encode)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 1436, in get_choices_data
    pairlist = list(self.selectcompute[field.number])
KeyError: 0
```

The error is not generated if the `choices` key is omitted from the code (generating a regular text input field).

The stack trace is not generated if the code segment is preceded by a another multiple choice field defined in yaml:

```yaml
mandatory: true
question: code generated fields and json representation
fields:
  - Something else: unrelated
    choices:
      - a
      - b
  - code: |
      [{"My label": "myfield",
       "choices": ["one","two"]
       }]
```

However, the resulting JSON representation of the question is not consisted with the question form:

```json
  "fields": [
    {
      "active": true,
      "choices": [
        {
          "label": "a",
          "value": "a"
        },
        {
          "label": "b",
          "value": "b"
        }
      ],
      "datatype": "text",
      "label": "Something else",
      "number": 0,
      "required": true,
      "validation_messages": {
        "required": "Detta fält är obligatoriskt."
      },
      "variable_name": "unrelated",
      "variable_name_encoded": "dW5yZWxhdGVk"
    },
    {
      "active": true,
      "choices": [
        {
          "label": "a",
          "value": "a"
        },
        {
          "label": "b",
          "value": "b"
        }
      ],
      "datatype": "text",
      "label": "Something else",
      "number": 0,
      "required": true,
      "validation_messages": {
        "required": "Detta fält är obligatoriskt."
      },
      "variable_name": "myfield",
      "variable_name_encoded": "bXlmaWVsZA"
    }
  ],
```

Note that, for code generated second field, the choices and label keys contains the values from the first yaml-defined field, while the variable name is correct.

**Comment by jhpyle** [comment]
I forgot to follow up to mention that I believe I fixed this issue in 1.4.73.
